version: '3'
services:
  apache:
    container_name: apache
    image: httpd:2.4
    volumes:
      - ./src:/data/www/html
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./httpd/log/error_log:/usr/local/apache2/logs/error_log
    depends_on:
      - php

  nginx:
    container_name: nginx
    image: nginx:1.13
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/data/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/log/access.log:/var/log/nginx/access.log
      - ./nginx/log/error.log:/var/log/nginx/error.log

    depends_on:
      - apache

  php:
    container_name: php_5.6
    build:
      ./php
    ports:
      - 9000:9000
    volumes:
      - ./src:/data/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d
      - ./mysql/dump/dump.sql:/docker-entrypoint-initdb.d/dump.sql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    links:
      - mysql:db
    ports:
      - 8183:80
    environment:
      MYSQL_ROOT_PASSWORD: 123456
